Name:           ros-kinetic-agile-grasp
Version:        0.8.3
Release:        0%{?dist}
Summary:        ROS agile_grasp package

Group:          Development/Libraries
License:        BSD
URL:            http://wiki.ros.org/agile_grasp
Source0:        %{name}-%{version}.tar.gz

Requires:       lapack-devel
Requires:       pcl
Requires:       pcl-tools
Requires:       ros-kinetic-cmake-modules
Requires:       ros-kinetic-eigen-conversions
Requires:       ros-kinetic-geometry-msgs
Requires:       ros-kinetic-message-runtime
Requires:       ros-kinetic-opencv3
Requires:       ros-kinetic-pcl-conversions
Requires:       ros-kinetic-roscpp
Requires:       ros-kinetic-sensor-msgs
Requires:       ros-kinetic-std-msgs
Requires:       ros-kinetic-tf
Requires:       ros-kinetic-tf-conversions
Requires:       ros-kinetic-visualization-msgs
BuildRequires:  lapack-devel
BuildRequires:  pcl-devel
BuildRequires:  ros-kinetic-catkin
BuildRequires:  ros-kinetic-cmake-modules
BuildRequires:  ros-kinetic-eigen-conversions
BuildRequires:  ros-kinetic-geometry-msgs
BuildRequires:  ros-kinetic-message-generation
BuildRequires:  ros-kinetic-opencv3
BuildRequires:  ros-kinetic-pcl-conversions
BuildRequires:  ros-kinetic-roscpp
BuildRequires:  ros-kinetic-sensor-msgs
BuildRequires:  ros-kinetic-std-msgs
BuildRequires:  ros-kinetic-tf-conversions
BuildRequires:  ros-kinetic-visualization-msgs

%description
The agile_grasp ROS package. AGILE stands for Antipodal Grasp Identification and
LEarning. The package finds antipodal grasps in point clouds. This fork is used
for research work at UTexas, Austin, with thanks to Andreas ten Pas. Most other
groups should use his original repository, instead.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/kinetic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/kinetic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/kinetic

%changelog
* Fri Mar 09 2018 Jack O'Quin <jack.oquin@gmail.com> - 0.8.3-0
- Autogenerated by Bloom

* Thu Mar 08 2018 Jack O'Quin <jack.oquin@gmail.com> - 0.8.2-0
- Autogenerated by Bloom

* Thu Mar 08 2018 Jack O'Quin <jack.oquin@gmail.com> - 0.8.1-0
- Autogenerated by Bloom

* Sat Mar 03 2018 Andreas ten Pas <atp@ccs.neu.edu> - 0.8.0-0
- Autogenerated by Bloom

